![dvd_image](dvd_image.jpg)

A DVD rental company needs your help! They want to figure out how many days a customer will rent a DVD for based on some features and has approached you for help. They want you to try out some regression models which will help predict the number of days a customer will rent a DVD for. The company wants a model which yeilds a MSE of 3 or less on a test set. The model you make will help the company become more efficient inventory planning.

The data they provided is in the csv file `rental_info.csv`. It has the following features:
- `"rental_date"`: The date (and time) the customer rents the DVD.
- `"return_date"`: The date (and time) the customer returns the DVD.
- `"amount"`: The amount paid by the customer for renting the DVD.
- `"amount_2"`: The square of `"amount"`.
- `"rental_rate"`: The rate at which the DVD is rented for.
- `"rental_rate_2"`: The square of `"rental_rate"`.
- `"release_year"`: The year the movie being rented was released.
- `"length"`: Lenght of the movie being rented, in minuites.
- `"length_2"`: The square of `"length"`.
- `"replacement_cost"`: The amount it will cost the company to replace the DVD.
- `"special_features"`: Any special features, for example trailers/deleted scenes that the DVD also has.
- `"NC-17"`, `"PG"`, `"PG-13"`, `"R"`: These columns are dummy variables of the rating of the movie. It takes the value 1 if the move is rated as the column name and 0 otherwise. For your convinience, the reference dummy has already been dropped.

In [17]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import LinearRegression, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeRegressor

from sklearn.preprocessing import StandardScaler
# Import any additional modules and start coding below

In [18]:
data = pd.read_csv('rental_info.csv', parse_dates = ['rental_date', 'return_date'])
data['rental_length_days'] = (data['return_date'] - data['rental_date']).dt.days
data.head()

                rental_date  ... rental_length_days
0 2005-05-25 02:54:33+00:00  ...                  3
1 2005-06-15 23:19:16+00:00  ...                  2
2 2005-07-10 04:27:45+00:00  ...                  7
3 2005-07-31 12:06:41+00:00  ...                  2
4 2005-08-19 12:30:04+00:00  ...                  4

[5 rows x 16 columns]

In [19]:
data['deleted_scenes'] = np.where(data['special_features'].str.contains('Deleted Scenes'), 1, 0)
data['behind_the_scenes'] = np.where(data['special_features'].str.contains('Behind the Scenes'), 1, 0)

In [20]:
data.head()

                rental_date  ... behind_the_scenes
0 2005-05-25 02:54:33+00:00  ...                 1
1 2005-06-15 23:19:16+00:00  ...                 1
2 2005-07-10 04:27:45+00:00  ...                 1
3 2005-07-31 12:06:41+00:00  ...                 1
4 2005-08-19 12:30:04+00:00  ...                 1

[5 rows x 18 columns]

In [21]:
kolumny = ['amount', 'release_year', 'rental_rate', 'length', 'replacement_cost', 'NC-17', 'PG', 'PG-13', 'R', 'amount_2', 'length_2', 'rental_rate_2', 'deleted_scenes', 'behind_the_scenes']
X = data[kolumny]
y = data['rental_length_days']
SEED = 9

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = SEED)

In [23]:
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(),
    "Decision Tree": DecisionTreeRegressor()
}

In [24]:
#Robimy lasso na wariatach
lasso = Lasso(alpha = 0.3, random_state = SEED)
lasso.fit(X_train, y_train)
lasso_coef = lasso.coef_
X_lasso_train, X_lasso_test = X_train.iloc[:, lasso_coef > 0], X_test.iloc[:, lasso_coef > 0]

In [25]:
#OLS
ols = LinearRegression()
ols.fit(X_lasso_train, y_train)
y_pred_ols = ols.predict(X_lasso_test)
ols_mse = mean_squared_error(y_pred_ols, y_test)

In [26]:
#Random Forest
parameters = {
    'n_estimators' : np.arange(1, 11, 1),
    'max_depth': np.arange(1, 11,1)
}
rf = RandomForestRegressor(random_state = SEED)
grid_search = GridSearchCV(rf, param_grid = parameters, cv=5)
grid_search.fit(X_train, y_train)
best_params = grid_search.best_params_
y_pred_grid = grid_search.predict(X_test)
grid_mse = mean_squared_error(y_test, y_pred_grid)

In [27]:
#model = RandomForestRegressor(n_estimators = best_params['n_estimators'], max_depth = #best_params['max_depth'], random_state = SEED)
#model.fit(X_train, y_train)
#y_pred_rf

In [28]:
#best_model = rf
#best_mse = grid_mse
best_params

{'max_depth': 10, 'n_estimators': 10}

In [29]:
best_model = rf
best_mse = grid_mse